### ISSUE TITLE
reflect: call of reflect.Value.Bytes on ptr Value on *json.RawMessage column

### ISSUE THREAD

**Issue by oiime** [uptrace/bun#11]
Hey, I'm probably trying to do something wrong but I've gotten `call of reflect.Value.Bytes on ptr Value` using this model struct:

```
type User struct {
	ID                 uuid.UUID        `bun:"type:uuid,default:uuid_generate_v4()"`
	Got 				*json.RawMessage
	Email              string
}
```
```
user = &User{
	ID:                 uuid,
	Got: 		    	otok,
	Email:              profile.EmailAddress,
}
```
This thing works fine:
```
if _, err := db.NewUpdate().Table("users").Model(&map[string]interface{}{"got": otok}).Where("id=?", user.ID).Exec(ctx); err != nil {
	return err
}
```
However this gives an error:
```
if _, err := db.NewUpdate().Column('got').Model(user).Where("id=?", user.ID).Exec(ctx); err != nil {
	return err
}
```
```
2021/05/28 11:36:13 http: panic serving [::1]:33166: reflect: call of reflect.Value.Bytes on ptr Value
goroutine 7 [running]:
net/http.(*conn).serve.func1(0xc00032c640)
	/rc/go/src/net/http/server.go:1824 +0x153
panic(0xfa0640, 0xc00081c1e0)
	/rc/go/src/runtime/panic.go:971 +0x499
reflect.flag.mustBe(...)
	/rc/go/src/reflect/value.go:221
reflect.Value.Bytes(0xfb2b20, 0xc0006264c0, 0x196, 0xc0006264b0, 0x199, 0x1)
	/rc/go/src/reflect/value.go:289 +0xfc
github.com/uptrace/bun/schema.appendJSONRawMessageValue(0x1262780, 0xc0004521e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0007e4000, 0x36, 0x1000, ...)
	/rc/gopath/pkg/mod/github.com/uptrace/bun@v0.1.14/schema/append_value.go:216 +0x4c
github.com/uptrace/bun/schema.(*Field).AppendValue(0xc00012eb00, 0x1262780, 0xc0004521e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0007e4000, 0x36, ...)
	/rc/gopath/pkg/mod/github.com/uptrace/bun@v0.1.14/schema/field.go:79 +0x1ed
github.com/uptrace/bun.(*UpdateQuery).appendSetStruct(0xc00012e840, 0x1262780, 0xc0004521e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0007e4000, 0x1d, ...)
	/rc/gopath/pkg/mod/github.com/uptrace/bun@v0.1.14/query_update.go:266 +0x457
github.com/uptrace/bun.(*UpdateQuery).mustAppendSet(0xc00012e840, 0x1262780, 0xc0004521e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0007e4000, 0x18, ...)
	/rc/gopath/pkg/mod/github.com/uptrace/bun@v0.1.14/query_update.go:218 +0x2e5
github.com/uptrace/bun.(*UpdateQuery).AppendQuery(0xc00012e840, 0x1262780, 0xc0004521e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0007e4000, 0x7, ...)
	/rc/gopath/pkg/mod/github.com/uptrace/bun@v0.1.14/query_update.go:174 +0x29e
github.com/uptrace/bun.(*UpdateQuery).Exec(0xc00012e840, 0x125c520, 0xc000110120, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/rc/gopath/pkg/mod/github.com/uptrace/bun@v0.1.14/query_update.go:312 +0x185
git.engelvoelkers.com/ev/go3/go3-misc/internal/services/user.(*Service).RegisterGoogleAuthCode(0xc00021f7f7, 0x125c520, 0xc000110120, 0x125f798, 0xc000328bd0, 0xc00013c000, 0x49, 0x7f36c5557778, 0xe916b6)
	/rc/rp/internal/services/user/auth.go:54 +0x66d
git.engelvoelkers.com/ev/go3/go3-misc/internal/api/routes.subscribeRoute(0x125f798, 0xc000328bd0, 0xc000132100, 0x203000, 0x41b21b, 0xc000110120, 0x30)
```

**Comment by vmihailenco** [comment]
Hi,

This should be fixed in v0.1.15. It also makes sense to replace `*json.RawMessage` with `json.RawMessage` because `*json.RawMessage` is defined as `[]byte`.

**Comment by oiime** [comment]
@vmihailenco Thanks, the reason for using *json.RawMessage is because json.RawMessage would not be very good at conveying NULL jsonb

**Comment by vmihailenco** [comment]
@oiime `json.RawMessage(nil)` should be marshaled as `NULL` (it is a recent improvement).
