### ISSUE TITLE
Panic when scanning model with self-join 

### ISSUE THREAD

**Issue by NathanBaulch** [uptrace/bun#158]
I'm getting a panic due to an uninitialized `structTableModel.strct` field when running the following code involving a model with a `has-one` relationship to itself. It looks like `initStruct` is never run because the `src` argument passed from `src.convertAssignRows` is nil.

```go
type Message struct {
	ID        uint64
	DeviceID  uint64
	ReplyToID uint64
	ReplyTo   *Message `bun:"rel:has-one,join:reply_to_id=id"`
}
panic(pdb.NewSelect().Model(&Message{ID: 2796, ReplyTo: &Message{}}).
	WherePK().
	ExcludeColumn("*").
	Relation("ReplyTo", func(q *bun.SelectQuery) *bun.SelectQuery { return q.Column("device_id") }).
	Scan(ctx))
```

```
panic: reflect: call of reflect.Value.Field on zero Value

goroutine 68 [running]:
reflect.Value.Field({0x0, 0x0, 0xa12d45}, 0x0)
	C:/Program Files/Go/src/reflect/value.go:1185 +0xef
github.com/uptrace/bun/schema.fieldByIndex({0x0, 0x0, 0xc000048698}, {0xc0006b8128, 0x8, 0xc000048680})
	C:/Users/Nathan/go/pkg/mod/github.com/uptrace/bun@v1.0.2/schema/reflect.go:31 +0x45
github.com/uptrace/bun/schema.(*Field).ScanValue(0xc0006b62c0, {0x0, 0x0, 0x9}, {0x0, 0x0})
	C:/Users/Nathan/go/pkg/mod/github.com/uptrace/bun@v1.0.2/schema/field.go:91 +0x5c
github.com/uptrace/bun.(*structTableModel).scanColumn(0xc000a980c0, {0xc00054020a, 0x9}, {0x0, 0x0})
	C:/Users/Nathan/go/pkg/mod/github.com/uptrace/bun@v1.0.2/model_table_struct.go:301 +0x19d
github.com/uptrace/bun.(*structTableModel).ScanColumn(0xc000a980c0, {0xc00054020a, 0x8}, {0x0, 0x0})
	C:/Users/Nathan/go/pkg/mod/github.com/uptrace/bun@v1.0.2/model_table_struct.go:284 +0x39
github.com/uptrace/bun.(*structTableModel).scanColumn(0xc000a98000, {0xc000540200, 0x13}, {0x0, 0x0})
	C:/Users/Nathan/go/pkg/mod/github.com/uptrace/bun@v1.0.2/model_table_struct.go:306 +0x162
github.com/uptrace/bun.(*structTableModel).ScanColumn(0xc000a98000, {0xc000540200, 0x187b240}, {0x0, 0x0})
	C:/Users/Nathan/go/pkg/mod/github.com/uptrace/bun@v1.0.2/model_table_struct.go:284 +0x39
github.com/uptrace/bun.(*structTableModel).Scan(0x0, {0x0, 0x0})
	C:/Users/Nathan/go/pkg/mod/github.com/uptrace/bun@v1.0.2/model_table_struct.go:280 +0xb3
database/sql.convertAssignRows({0x187b240, 0xc000a98000}, {0x0, 0x0}, 0xc00050c080)
	C:/Program Files/Go/src/database/sql/convert.go:385 +0x21a2
database/sql.(*Rows).Scan(0xc00050c080, {0xc0004280e0, 0x1, 0xc000692858})
	C:/Program Files/Go/src/database/sql/sql.go:3246 +0x366
github.com/uptrace/bun.(*structTableModel).scanRow(0xc000a98000, {0x1b32478, 0xc000a8a0f0}, 0x100c000a8a0f0, {0xc0004280e0, 0x1, 0x1})
	C:/Users/Nathan/go/pkg/mod/github.com/uptrace/bun@v1.0.2/model_table_struct.go:265 +0x73
github.com/uptrace/bun.(*structTableModel).ScanRow(0xc000a98000, {0x1b32478, 0xc000a8a0f0}, 0xc000a8c080)
	C:/Users/Nathan/go/pkg/mod/github.com/uptrace/bun@v1.0.2/model_table_struct.go:256 +0x9e
github.com/uptrace/bun.(*structTableModel).ScanRows(0xc000048270, {0x1b32478, 0xc000a8a0f0}, 0xc000aa0000)
	C:/Users/Nathan/go/pkg/mod/github.com/uptrace/bun@v1.0.2/model_table_struct.go:229 +0x51
github.com/uptrace/bun.(*baseQuery).scan(0xc0005024e0, {0x1b32478, 0xc0006965a0}, {0x1b15c60, 0xc0005024e0}, {0xc000aa0000, 0xb4}, {0x1b26ec0, 0xc000a98000}, 0x1)
	C:/Users/Nathan/go/pkg/mod/github.com/uptrace/bun@v1.0.2/query_base.go:444 +0x17a
github.com/uptrace/bun.(*SelectQuery).Scan(0xc0005024e0, {0x1b32478, 0xc0006965a0}, {0x0, 0x1, 0xc0006ae000})
	C:/Users/Nathan/go/pkg/mod/github.com/uptrace/bun@v1.0.2/query_select.go:694 +0x14e
```

Creating a second dummy message struct fixes the problem.

```go
type MessageX struct {
	bun.BaseModel `bun:"message"`
	ID        uint64
	DeviceID  uint64
}
type Message struct {
	bun.BaseModel `bun:"message"`
	ID        uint64
	ReplyToID uint64
	ReplyTo   *MessageX `bun:"rel:has-one,join:reply_to_id=id"`
}
```

**Comment by vmihailenco** [comment]
Thanks for the report. The relation probably should be `rel:belongs-to` and then `join:reply_to_id=id` can be removed.
