### ISSUE TITLE
[PostgreSQL] NOW() resulting panic

### ISSUE THREAD

**Issue by l0nax** [uptrace/bun#175]
Thanks for publishing this nice library, it really simplifies writing queries and improves the code readability :+1: 

#### Description

The following code results into a panic/ segmentation fault:
```go
// NeedGeoIPUpdate returns if the GeoIP DB needs to be updated.
func NeedGeoIPUpdate(ctx context.Context) (bool, error) {
	var ret bool

	sel := db.NewSelect().
		Table("system_info").
		Column("id").
		Where("last_geoip_update < NOW() - INTERVAL '14 days'") // GeoIP DB is updated every two weeks

	err := db.NewSelect().
		ColumnExpr("EXISTS(?)", sel).
		Scan(ctx, &ret)

	return ret, err
}
```

But the following test code snippet works:
```go
        err := db.NewSelect().
                Model(&s).
                Where("last_geoip_update < NOW() - INTERVAL '14 days'"). // GeoIP DB is updated every two weeks
                Scan(context.Background())
```

and this one _not_:
```go
        err := db.NewSelect().
                Table("system_info").
                Column("last_geoip_update").
                Column("id").
                Where("last_geoip_update < NOW() - INTERVAL '14 days'"). // GeoIP DB is updated every two weeks
                Scan(context.Background(), &s)
```

The documentation does not document that the `Model` method call is required.
As from my point of view, it more looks like a bug – please correct me if I'm wrong.

**Comment by vmihailenco** [comment]
`Model` is not required and this indeed looks like a bug. How the panic looks like?

We have a test that looks like your code - https://github.com/uptrace/bun/blob/master/internal/dbtest/db_test.go#L248-L263. It would be nice if you can provide something similar that I can run.

**Comment by l0nax** [comment]
Here's the panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x118 pc=0x92621f]

goroutine 21 [running]:
github.com/uptrace/bun.(*SelectQuery).appendColumns(0xc000583040, {{0x13808c0, 0xc0003d2180}, 0xc00000c0f0}, {0xc000294000, 0x15, 0x1000})
        /root/.go/pkg/mod/github.com/uptrace/bun@v1.0.4/query_select.go:527 +0x69f
github.com/uptrace/bun.(*SelectQuery).appendQuery(0xc000583040, {{0x13808c0, 0xc0003d2180}, 0xc00000c0d8}, {0xc000294000, 0x15, 0x1000}, 0x0)
        /root/.go/pkg/mod/github.com/uptrace/bun@v1.0.4/query_select.go:409 +0x5d4
github.com/uptrace/bun.(*SelectQuery).AppendQuery(0x400, {{0x13808c0, 0xc0003d2180}, 0xc00000c0d8}, {0xc000294000, 0xc000608720, 0x41764b})
        /root/.go/pkg/mod/github.com/uptrace/bun@v1.0.4/query_select.go:363 +0x30
github.com/uptrace/bun/schema.Formatter.appendArg({{0x13808c0, 0xc0003d2180}, 0xc00000c0d8}, {0xc000294000, 0xe, 0x1000}, {0x1107fe0, 0xc000583040})
        /root/.go/pkg/mod/github.com/uptrace/bun@v1.0.4/schema/formatter.go:164 +0x157
github.com/uptrace/bun/schema.Formatter.append({{0x13808c0, 0xc0003d2180}, 0xc00000c0d8}, {0xc000294000, 0x7, 0x1000}, 0xc0002a78d8, {0xc000424400, 0x1, 0x1})
        /root/.go/pkg/mod/github.com/uptrace/bun@v1.0.4/schema/formatter.go:155 +0x44f
github.com/uptrace/bun/schema.Formatter.AppendQuery({{0x13808c0, 0xc0003d2180}, 0xc00000c0d8}, {0xc000294000, 0x7, 0x1000}, {0x113158d, 0x203000}, {0xc000424400, 0x1, ...})
        /root/.go/pkg/mod/github.com/uptrace/bun@v1.0.4/schema/formatter.go:86 +0x1dd
github.com/uptrace/bun/schema.QueryWithArgs.AppendQuery({{0x113158d, 0x9}, {0xc000424400, 0x1, 0x1}}, {{0x13808c0, 0xc0003d2180}, 0xc00000c0d8}, {0xc000294000, 0x7, ...})
        /root/.go/pkg/mod/github.com/uptrace/bun@v1.0.4/schema/sqlfmt.go:61 +0xae
github.com/uptrace/bun.(*SelectQuery).appendColumns(0xc0005836c0, {{0x13808c0, 0xc0003d2180}, 0xc00000c0d8}, {0xc000294000, 0x7, 0x1000})
        /root/.go/pkg/mod/github.com/uptrace/bun@v1.0.4/query_select.go:535 +0x94e
github.com/uptrace/bun.(*SelectQuery).appendQuery(0xc0005836c0, {{0x13808c0, 0xc0003d2180}, 0x0}, {0xc000294000, 0x7, 0x1000}, 0x0)
        /root/.go/pkg/mod/github.com/uptrace/bun@v1.0.4/query_select.go:409 +0x5d4
github.com/uptrace/bun.(*SelectQuery).AppendQuery(...)
        /root/.go/pkg/mod/github.com/uptrace/bun@v1.0.4/query_select.go:363
github.com/uptrace/bun.(*SelectQuery).Scan(0xc0005836c0, {0x136e6a0, 0xc00003c050}, {0xc000424410, 0x0, 0xc0004719b0})
        /root/.go/pkg/mod/github.com/uptrace/bun@v1.0.4/query_select.go:687 +0x110
gitlab.fabmation.info/deserve/server/models.NeedGeoIPUpdate({0x136e6a0, 0xc00003c050})
        /root/.go/src/gitlab.fabmation.info/deserve/server/models/systemInfo.go:43 +0x556
gitlab.fabmation.info/deserve/server/handler.geoipDBUpdater()
        /root/.go/src/gitlab.fabmation.info/deserve/server/handler/handler.go:125 +0xa6
created by gitlab.fabmation.info/deserve/server/handler.StartServer
        /root/.go/src/gitlab.fabmation.info/deserve/server/handler/handler.go:101 +0x729
```
