### ISSUE TITLE
[PostgreSQL] CTEs as VALUEs holder resulting in panic

### ISSUE THREAD

**Issue by l0nax** [uptrace/bun#179]
Please note that I'm unsure if I'm using the library correctly as it's not clear to me if the usage of `NewValues()` is in this context here correct.

SQL Query:
```sql
WITH input(machine_id_hash) AS (
    VALUES (bytea 'asdasdasdasd')
), ins AS (
    INSERT INTO requestee_machine_id(machine_id_hash)
    SELECT * FROM input
    ON CONFLICT (machine_id_hash) DO NOTHING
    RETURNING id
)
SELECT id
FROM ins

UNION ALL

SELECT m.id
FROM input
JOIN requestee_machine_id m USING(machine_id_hash);
```

GoLang Code:
```go
type RequesteeMachineID struct {
	bun.BaseModel `bun:"requestee_machine_id"`

	ID            int64
	MachineIDHash []byte `bun:"machine_id_hash"`
}

// InsertMachineHash inserts the given ID/ Hash if it does not exists and returns the
// corresponding ID.
func InsertMachineHash(ctx context.Context, hash []byte) (int64, error) {
	var id int64

	input := db.NewValues((*RequesteeMachineID)(nil)).
		Value("machine_id_hash", "bytea ?", hash)

	insert := db.NewInsert().
		TableExpr("requestee_machine_id(machine_id_hash)").
		TableExpr("input").
		On("CONFLICT (machine_id_hash) DO NOTHING").
		Returning("id")

	err := db.NewSelect().
		With("input", input).
		With("ins", insert).
		Column("id").
		TableExpr("ins").
		UnionAll(
			db.NewSelect().
				Column("m.id").
				ModelTableExpr("input").
				Join("JOIN requestee_machine_id m USING(machine_id_hash)"),
		).
		Limit(1).
		Scan(ctx, &id)

	return id, err
}
```

Resulting panic:
```
panic: reflect: call of reflect.Value.Field on zero Value [recovered]
        panic: reflect: call of reflect.Value.Field on zero Value

goroutine 36 [running]:
go.opentelemetry.io/otel/sdk/trace.(*span).End·dwrap·11()
        /root/.go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.0.0-!r!c2/trace/span.go:240 +0x2a
go.opentelemetry.io/otel/sdk/trace.(*span).End(0xc00001c000, {0x0, 0x0, 0x0})
        /root/.go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.0.0-!r!c2/trace/span.go:274 +0x6fe
panic({0xff3300, 0xc000694d08})
        /root/.gvm/gos/go1.17/src/runtime/panic.go:1038 +0x215
reflect.Value.Field({0x0, 0x0, 0xb}, 0x0)
        /root/.gvm/gos/go1.17/src/reflect/value.go:1185 +0xef
github.com/uptrace/bun/schema.fieldByIndex({0x0, 0x0, 0xf}, {0xc0002b3770, 0x1, 0x1})
        /root/.go/pkg/mod/github.com/uptrace/bun@v1.0.5/schema/reflect.go:31 +0x45
github.com/uptrace/bun/schema.(*Field).AppendValue(0xc000133080, {{0x1381de0, 0xc00052c480}, 0xc000694cf0}, {0xc000139000, 0x34, 0x1000}, {0x0, 0x0, 0x0})
        /root/.go/pkg/mod/github.com/uptrace/bun@v1.0.5/schema/field.go:68 +0xab
github.com/uptrace/bun.(*ValuesQuery).appendValues(0xc0004acd20, {{0x1381de0, 0xc00052c480}, 0xc000694cf0}, {0xc000139000, 0x34, 0x1000}, {0xc000694c78, 0x2, 0x3}, ...)
        /root/.go/pkg/mod/github.com/uptrace/bun@v1.0.5/query_values.go:203 +0x2e5
github.com/uptrace/bun.(*ValuesQuery).appendQuery(0xc0004acd20, {{0x1381de0, 0xc00052c480}, 0xc000694cf0}, {0xc000139000, 0xc000694c78, 0x2}, {0xc000694c78, 0x2, 0x3})
        /root/.go/pkg/mod/github.com/uptrace/bun@v1.0.5/query_values.go:141 +0x2c9
github.com/uptrace/bun.(*ValuesQuery).AppendQuery(0xc0004acd20, {{0x1381de0, 0xc00052c480}, 0xc000694cc0}, {0xc000139000, 0x2c, 0x1000})
        /root/.go/pkg/mod/github.com/uptrace/bun@v1.0.5/query_values.go:116 +0x1bd
github.com/uptrace/bun.(*baseQuery).appendWith(0x1381de0, {{0x1381de0, 0xc00052c480}, 0xc000694cc0}, {0xc000139000, 0x0, 0xc00047f320})
        /root/.go/pkg/mod/github.com/uptrace/bun@v1.0.5/query_base.go:212 +0x43d
github.com/uptrace/bun.(*SelectQuery).appendQuery(0xc0004ea1a0, {{0x1381de0, 0xc00052c480}, 0x0}, {0xc000139000, 0x1, 0x1000}, 0x0)
        /root/.go/pkg/mod/github.com/uptrace/bun@v1.0.5/query_select.go:387 +0x29a
github.com/uptrace/bun.(*SelectQuery).AppendQuery(...)
        /root/.go/pkg/mod/github.com/uptrace/bun@v1.0.5/query_select.go:367
github.com/uptrace/bun.(*SelectQuery).Scan(0xc0004ea1a0, {0x136fc30, 0xc0004438c0}, {0xc000541970, 0x7, 0xc000541960})
        /root/.go/pkg/mod/github.com/uptrace/bun@v1.0.5/query_select.go:691 +0x110
gitlab.fabmation.info/deserve/server/models.InsertMachineHash({0x136fc30, 0xc0004438c0}, {0xc00040e1e0, 0x20, 0x21})
        /root/.go/src/gitlab.fabmation.info/deserve/server/models/requesteeMachineID.go:69 +0xd4d
gitlab.fabmation.info/deserve/server/handler/apiV1.UpdateCheckHandler(0xc00030a840)
        /root/.go/src/gitlab.fabmation.info/deserve/server/handler/apiV1/update.go:694 +0x89f
gitlab.fabmation.info/deserve/server/handler/helper/auth.HasProject.func1(0xc0003684d0)
        /root/.go/src/gitlab.fabmation.info/deserve/server/handler/helper/auth/auth.go:189 +0x15a
github.com/gofiber/fiber/v2.(*App).next(0xc000102d00, 0xc00030a840)
        /root/.go/pkg/mod/github.com/gofiber/fiber/v2@v2.18.0/router.go:127 +0x1d8
github.com/gofiber/fiber/v2.(*Ctx).Next(0x10c2240)
        /root/.go/pkg/mod/github.com/gofiber/fiber/v2@v2.18.0/ctx.go:709 +0x53
gitlab.fabmation.info/deserve/server/handler.AuthMiddelware(0xc0007a0ef8)
        /root/.go/src/gitlab.fabmation.info/deserve/server/handler/auth_middelware.go:63 +0x316
github.com/gofiber/fiber/v2.(*Ctx).Next(0x1)
        /root/.go/pkg/mod/github.com/gofiber/fiber/v2@v2.18.0/ctx.go:706 +0x43
gitlab.fabmation.info/deserve/server/handler/middleware/accesslog.New.func3(0xc00030a840)
        /root/.go/src/gitlab.fabmation.info/deserve/server/handler/middleware/accesslog/accesslog.go:84 +0xb8
github.com/gofiber/fiber/v2.(*Ctx).Next(0xc0007a1330)
        /root/.go/pkg/mod/github.com/gofiber/fiber/v2@v2.18.0/ctx.go:706 +0x43
gitlab.fabmation.info/deserve/server/handler/middleware/ftracer.New.func1(0xc00030a840)
        /root/.go/src/gitlab.fabmation.info/deserve/server/handler/middleware/ftracer/tracer.go:50 +0x1357
github.com/gofiber/fiber/v2.(*Ctx).Next(0xc000018430)
        /root/.go/pkg/mod/github.com/gofiber/fiber/v2@v2.18.0/ctx.go:706 +0x43
gitlab.fabmation.info/deserve/server/handler/middleware.NewRequestID(0xc00030a840)
        /root/.go/src/gitlab.fabmation.info/deserve/server/handler/middleware/requestid.go:18 +0x152
github.com/gofiber/fiber/v2.(*App).next(0xc000102d00, 0xc00030a840)
        /root/.go/pkg/mod/github.com/gofiber/fiber/v2@v2.18.0/router.go:127 +0x1d8
github.com/gofiber/fiber/v2.(*App).handler(0xc000102d00, 0x485517)
        /root/.go/pkg/mod/github.com/gofiber/fiber/v2@v2.18.0/router.go:155 +0xe5
github.com/valyala/fasthttp.(*Server).serveConn(0xc00035ce00, {0x137ea70, 0xc00000e598})
        /root/.go/pkg/mod/github.com/valyala/fasthttp@v1.30.0/server.go:2266 +0x122d
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc0004006e0, 0xc000494060)
        /root/.go/pkg/mod/github.com/valyala/fasthttp@v1.30.0/workerpool.go:223 +0xa9
github.com/valyala/fasthttp.(*workerPool).getCh.func1()
        /root/.go/pkg/mod/github.com/valyala/fasthttp@v1.30.0/workerpool.go:195 +0x38
created by github.com/valyala/fasthttp.(*workerPool).getCh
        /root/.go/pkg/mod/github.com/valyala/fasthttp@v1.30.0/workerpool.go:194 +0x1b5
```

**Comment by vmihailenco** [comment]
This is not currently supported:

```go
	input := db.NewValues((*RequesteeMachineID)(nil)).
		Value("machine_id_hash", "bytea ?", hash)
```

You can try:

```go
	input := db.NewValues([]RequesteeMachineID{{MachineIDHash: []byte("hello")}})
```

I am not sure that the original query should be supported, because `Value` is used to overwrite existing values, not to build `VALUES` query.

**Comment by l0nax** [comment]
You're example works.

Thanks a lot!
