### ISSUE TITLE
`panic: unaligned 64-bit atomic operation` running on 32 bit arm architecture

### ISSUE THREAD

**Issue by tsmethurst** [uptrace/bun#212]
Hi! I'm trying to run GoToSocial on a Raspberry Pi Zero W, which uses 32 bit arm architecture. GoToSocial uses Bun for sqlite and postgres connections. Unfortunately, I run into the following panic when running gts on my pi:

```
panic: unaligned 64-bit atomic operation

goroutine 1 [running]:
runtime/internal/atomic.panicUnaligned()
	/usr/local/go/src/runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Xadd64(0x3082214, 0x1)
	/usr/local/go/src/runtime/internal/atomic/atomic_arm.s:256 +0x14
github.com/uptrace/bun.(*DB).beforeQuery(0x30821e0, {0x1be8ee0, 0x2c28608}, {0x1be6624, 0x30b11e0}, {0x3048000, 0xb5}, {0x0, 0x0, 0x0})
	/home/tobi/go/src/github.com/superseriousbusiness/gotosocial/vendor/github.com/uptrace/bun/hook.go:56 +0x34
github.com/uptrace/bun.(*baseQuery).exec(0x30b11e0, {0x1be8ee0, 0x2c28608}, {0x1be6624, 0x30b11e0}, {0x3048000, 0xb5})
	/home/tobi/go/src/github.com/superseriousbusiness/gotosocial/vendor/github.com/uptrace/bun/query_base.go:465 +0x64
github.com/uptrace/bun.(*CreateTableQuery).Exec(0x30b11e0, {0x1be8ee0, 0x2c28608}, {0x0, 0x0, 0x0})
	/home/tobi/go/src/github.com/superseriousbusiness/gotosocial/vendor/github.com/uptrace/bun/query_table_create.go:254 +0xf0
github.com/uptrace/bun/migrate.(*Migrator).Init(0x306b3b0, {0x1be8ee0, 0x2c28608})
	/home/tobi/go/src/github.com/superseriousbusiness/gotosocial/vendor/github.com/uptrace/bun/migrate/migrator.go:87 +0x1a8
github.com/superseriousbusiness/gotosocial/internal/db/bundb.doMigration({0x1be8ee0, 0x2c28608}, 0x30821e0, 0x308ca40)
	/home/tobi/go/src/github.com/superseriousbusiness/gotosocial/internal/db/bundb/bundb.go:84 +0x90
github.com/superseriousbusiness/gotosocial/internal/db/bundb.NewBunDBService({0x1be8ee0, 0x2c28608}, 0x3080460, 0x308ca40)
	/home/tobi/go/src/github.com/superseriousbusiness/gotosocial/internal/db/bundb/bundb.go:169 +0xa0c
github.com/superseriousbusiness/gotosocial/internal/cliactions/server.glob..func1({0x1be8ee0, 0x2c28608}, 0x3080460, 0x308ca40)
	/home/tobi/go/src/github.com/superseriousbusiness/gotosocial/internal/cliactions/server/server.go:55 +0x38
main.runAction(0x305be80, 0x18b51ec)
	/home/tobi/go/src/github.com/superseriousbusiness/gotosocial/cmd/gotosocial/runaction.go:50 +0x22c
main.serverCommands.func1(0x305be80)
	/home/tobi/go/src/github.com/superseriousbusiness/gotosocial/cmd/gotosocial/servercommands.go:36 +0x28
github.com/urfave/cli/v2.(*Command).Run(0x2f70b40, 0x305be00)
	/home/tobi/go/src/github.com/superseriousbusiness/gotosocial/vendor/github.com/urfave/cli/v2/command.go:163 +0x650
github.com/urfave/cli/v2.(*App).RunAsSubcommand(0x2c7eb60, 0x305bd80)
	/home/tobi/go/src/github.com/superseriousbusiness/gotosocial/vendor/github.com/urfave/cli/v2/app.go:434 +0x90c
github.com/urfave/cli/v2.(*Command).startApp(0x2f70ab0, 0x305bd80)
	/home/tobi/go/src/github.com/superseriousbusiness/gotosocial/vendor/github.com/urfave/cli/v2/command.go:278 +0x7e4
github.com/urfave/cli/v2.(*Command).Run(0x2f70ab0, 0x305bd80)
	/home/tobi/go/src/github.com/superseriousbusiness/gotosocial/vendor/github.com/urfave/cli/v2/command.go:94 +0x7ac
github.com/urfave/cli/v2.(*App).RunContext(0x2c7ea90, {0x1be8ee0, 0x2c28608}, {0x2c24060, 0x5, 0x6})
	/home/tobi/go/src/github.com/superseriousbusiness/gotosocial/vendor/github.com/urfave/cli/v2/app.go:313 +0x760
github.com/urfave/cli/v2.(*App).Run(...)
	/home/tobi/go/src/github.com/superseriousbusiness/gotosocial/vendor/github.com/urfave/cli/v2/app.go:224
main.main()
	/home/tobi/go/src/github.com/superseriousbusiness/gotosocial/cmd/gotosocial/main.go:76 +0x1cc
```

**Comment by NyaaaWhatsUpDoc** [comment]
Useful reference, this is how Go standard libraries deal with atomic counters across multiple architectures: https://github.com/golang/go/blob/13aa0d8f578e9c293970fe462f79655899959093/src/sync/waitgroup.go#L23

**Comment by tsmethurst** [comment]
Thank you, it works now on `arm` 32 bit :)
