### ISSUE TITLE
Update with shopspring/decimal nil pointers panics

### ISSUE THREAD

**Issue by pehlert** [uptrace/bun#444]
Hello all,

When attempting an update with a `nil` pointer on a shopspring/decimal type, we are getting the following panic:

```
app_1       | 2022/02/17 11:25:45 stderr: panic: value method github.com/shopspring/decimal.Decimal.Value called using nil *Decimal pointer
app_1       | 2022/02/17 11:25:45 stderr:
app_1       | 2022/02/17 11:25:45 stderr: goroutine 1 [running]:
app_1       | 2022/02/17 11:25:45 stderr: github.com/shopspring/decimal.(*Decimal).Value(0x0)
app_1       | 2022/02/17 11:25:45 stderr: 	<autogenerated>:1 +0x84
app_1       | 2022/02/17 11:25:45 stderr: github.com/uptrace/bun/schema.appendDriverValue({{0x2feb98, 0x4000182be0}, 0x400000eab0}, {0x40001b7000, 0x28, 0x1000}, {0x29bac0, 0x400000ea70, 0x196})
app_1       | 2022/02/17 11:25:45 stderr: 	/go/pkg/mod/github.com/uptrace/bun@v1.0.22/schema/append_value.go:256 +0x74
app_1       | 2022/02/17 11:25:45 stderr: github.com/uptrace/bun/schema.(*Field).AppendValue(0x40001b26e0, {{0x2feb98, 0x4000182be0}, 0x400000eab0}, {0x40001b7000, 0x28, 0x1000}, {0x284680, 0x400000ea68, 0x199})
app_1       | 2022/02/17 11:25:45 stderr: 	/go/pkg/mod/github.com/uptrace/bun@v1.0.22/schema/field.go:79 +0x188
app_1       | 2022/02/17 11:25:45 stderr: github.com/uptrace/bun.(*UpdateQuery).appendSetStruct(0x4000116a80, {{0x2feb98, 0x4000182be0}, 0x400000eab0}, {0x40001b7000, 0x1b, 0x1000}, 0x40001223c0)
app_1       | 2022/02/17 11:25:45 stderr: 	/go/pkg/mod/github.com/uptrace/bun@v1.0.22/query_update.go:289 +0x400
app_1       | 2022/02/17 11:25:45 stderr: github.com/uptrace/bun.(*UpdateQuery).mustAppendSet(0x4000116a80, {{0x2feb98, 0x4000182be0}, 0x400000eab0}, {0x40001b7000, 0x16, 0x1000})
app_1       | 2022/02/17 11:25:45 stderr: 	/go/pkg/mod/github.com/uptrace/bun@v1.0.22/query_update.go:241 +0x1e4
app_1       | 2022/02/17 11:25:45 stderr: github.com/uptrace/bun.(*UpdateQuery).AppendQuery(0x4000116a80, {{0x2feb98, 0x4000182be0}, 0x0}, {0x40001b7000, 0x0, 0x1000})
app_1       | 2022/02/17 11:25:45 stderr: 	/go/pkg/mod/github.com/uptrace/bun@v1.0.22/query_update.go:197 +0x234
app_1       | 2022/02/17 11:25:45 stderr: github.com/uptrace/bun.(*UpdateQuery).Exec(0x4000116a80, {0x2fb750, 0x4000018080}, {0x0, 0x0, 0x0})
app_1       | 2022/02/17 11:25:45 stderr: 	/go/pkg/mod/github.com/uptrace/bun@v1.0.22/query_update.go:406 +0x114
app_1       | 2022/02/17 11:25:45 stderr: main.main()
app_1       | 2022/02/17 11:25:45 stderr: 	/app/main.go:33 +0x350
```

This can be "resolved" by setting the `nullzero` property on the attribute. Then however there is no way to store the actual value "0" (as a number) anymore as that will also be converted to `NULL`.

We are using the latest versions of decimal (1.3.1) and bun (1.0.22) on a Postgres database.

The following screenshot shows some demo code and the error message:

<img width="2560" alt="Screenshot 2022-02-17 at 12 25 52" src="https://user-images.githubusercontent.com/9256/154472521-eb1d84ea-4e78-4b93-8bad-89ae28b5b2e7.png">

Is this a bug or am I missing something?

**Comment by pehlert** [comment]
Thanks for getting back @vmihailenco - let me know if you need anything else to reproduce this.
