### ISSUE TITLE
panic: can't find m2m table

### ISSUE THREAD

**Issue by periode** [uptrace/bun#623]
Hello,

I'm running into an issue with a `many2many` relationship, where the m2m table isn't being picked up by Bun and throws a panic when I try to register other models or use `.Relation()` on a query. 

I have a Syllabus, which can be featured in many Collections, and a Collection can have many Syllabus:

```go
type Syllabus struct {
	ID        uuid.UUID `bun:",pk,type:uuid,default:uuid_generate_v4()"`
	CreatedAt time.Time `bun:",nullzero,notnull,default:current_timestamp" json:"created_at"`
	UpdatedAt time.Time `bun:",nullzero,notnull,default:current_timestamp" json:"updated_at"`

	Collections []Collection `bun:"m2m:collection_to_syllabus,join:Syllabus=Collection"`
	Title       string       `bun:",notnull" json:"title" form:"title"`
}

type Collection struct {
	ID        uuid.UUID `bun:",pk,type:uuid,default:uuid_generate_v4()"`
	CreatedAt time.Time `bun:",nullzero,notnull,default:current_timestamp" json:"created_at"`
	UpdatedAt time.Time `bun:",nullzero,notnull,default:current_timestamp" json:"updated_at"`

	Syllabi []Syllabus `bun:"m2m:collection_to_syllabus,join:Collection=Syllabus" json:"syllabi"`
	Name    string     `json:"name" form:"name" binding:"required"`
}

type CollectionToSyllabus struct {
	CreatedAt    time.Time   `bun:",notnull,default:current_timestamp" json:"created_at"`
	CollectionID uuid.UUID   `bun:",pk,type:uuid"`
	Collection   *Collection `bun:"rel:belongs-to,join:collection_id=id"`
	SyllabusID   uuid.UUID   `bun:",pk,type:uuid"`
	Syllabus     *Syllabus   `bun:"rel:belongs-to,join:syllabus_id=id"`
}
```

My migration for creating the m2m table happens like this:
```sql
CREATE TABLE IF NOT EXISTS collection_to_syllabus(
    collection_id uuid DEFAULT gen_random_uuid() NOT NULL,
    syllabus_id uuid DEFAULT gen_random_uuid() NOT NULL,
    created_at timestamp NOT NULL,
    CONSTRAINT collection_syllabus_pk PRIMARY KEY(collection_id, syllabus_id)
);
```

I then initialize the database like this, registering the `CollectionToSyllabus` as early as possible:
```go
func InitDB(url string) (*bun.DB, error) {
	sslMode := false
	if strings.HasSuffix(url, "sslmode=require") {
		sslMode = true
	}

	sqldb := sql.OpenDB(pgdriver.NewConnector(pgdriver.WithDSN(url), pgdriver.WithInsecure(!sslMode)))
	db = bun.NewDB(sqldb, pgdialect.New())
	db.RegisterModel((*CollectionToSyllabus)(nil))

	err := db.Ping()
	if err != nil {
		return db, err
	}

	err = runMigrations(url, sslMode)
	if err != nil {
		zero.Errorf("error running migrations: %v", err)
		log.Fatal(err)
	}

	err = runFixtures()
	if err != nil {
		zero.Errorf("error running fixtures: %v", err)
		return db, err
	}

	return db, err
}
```

The issue happens with the `runFixtures()` function, which is also registering models:
```go
func runFixtures() error {
	db.RegisterModel(
		(*Syllabus)(nil),
		(*Resource)(nil),
		(*User)(nil),
		(*Collection)(nil),
	)
	fixture := dbfixture.New(db, dbfixture.WithTruncateTables())
	ctx := context.Background()
	_ = fixture.Load(ctx, os.DirFS(Basepath+"/fixtures"), "syllabus.yml", "resource.yml", "user.yml", "collection.yml", "collection_to_syllabus.yml")
	return nil
}
```

And then I get this panic during the second model registration in `runFixtures()`:

```
panic: bun: can't find m2m collection_to_syllabus table (use db.RegisterModel)                                         
                                                                                                                       
goroutine 1 [running]:                                                                                                 
github.com/uptrace/bun/schema.(*Table).m2mRelation(0xc0000b09a0, 0xc0000b18c0)  
        /home/pierre/go/pkg/mod/github.com/uptrace/bun@v1.1.6/schema/table.go:752 +0x9e5                               
github.com/uptrace/bun/schema.(*Table).tryRelation(0xc0000b09a0, 0xc0000b18c0)  
        /home/pierre/go/pkg/mod/github.com/uptrace/bun@v1.1.6/schema/table.go:435 +0x176                               
github.com/uptrace/bun/schema.(*Table).initRelations(0xc0000b09a0)                                                     
        /home/pierre/go/pkg/mod/github.com/uptrace/bun@v1.1.6/schema/table.go:416 +0x6f                                
github.com/uptrace/bun/schema.(*Table).init2(0x47c126?)    
        /home/pierre/go/pkg/mod/github.com/uptrace/bun@v1.1.6/schema/table.go:130 +0x19
github.com/uptrace/bun/schema.(*tableInProgress).init2.func1()                   
        /home/pierre/go/pkg/mod/github.com/uptrace/bun@v1.1.6/schema/tables.go:34 +0x29
sync.(*Once).doSlow(0xd4f1e0?, 0xc0000ae000?)
        /usr/lib/go/src/sync/once.go:68 +0xc2
sync.(*Once).Do(...)
        /usr/lib/go/src/sync/once.go:59
github.com/uptrace/bun/schema.(*tableInProgress).init2(0xc00010e518?)
        /home/pierre/go/pkg/mod/github.com/uptrace/bun@v1.1.6/schema/tables.go:33 +0x5a
github.com/uptrace/bun/schema.(*Tables).table(0xc00010e4e0, {0xd4f1e0?, 0xbdc6e0?}, 0x0)
        /home/pierre/go/pkg/mod/github.com/uptrace/bun@v1.1.6/schema/tables.go:104 +0x27f
github.com/uptrace/bun/schema.(*Tables).Get(...)
        /home/pierre/go/pkg/mod/github.com/uptrace/bun@v1.1.6/schema/tables.go:62
github.com/uptrace/bun/schema.(*Tables).Register(0x8ff7c5?, {0xc00044dcc0?, 0x4, 0x2c?})
        /home/pierre/go/pkg/mod/github.com/uptrace/bun@v1.1.6/schema/tables.go:57 +0xa5
github.com/uptrace/bun.(*DB).RegisterModel(0xc4a339?, {0xc00044dcc0, 0x4, 0x4})
        /home/pierre/go/pkg/mod/github.com/uptrace/bun@v1.1.6/db.go:193 +0x45
github.com/commonsyllabi/explorer/api/models.runFixtures()
        /home/pierre/code/commonsyllabi/explorer/api/models/db.go:118 +0xaa
github.com/commonsyllabi/explorer/api/models.InitDB({0xc000174400, 0x34})
        /home/pierre/code/commonsyllabi/explorer/api/models/db.go:52 +0x2a5
main.main()
        /home/pierre/code/commonsyllabi/explorer/cmd/api/main.go:47 +0x448
exit status 2
2022/07/21 17:18:42 exit status 1
```

So there seems to be some sort of conflict in registering models (unless I'm doing something wrong), since I can see that the table is properly created in postgres, the correct `collection_to_syllabus` name. Any pointers would be appreciated.

Thank you!

**Comment by vmihailenco** [comment]
By default, `CollectionToSyllabus`, will have `collection_to_syllabuses` table name and you are using `collection_to_syllabus`.

But that is a guess. Please provide proper https://stackoverflow.com/help/minimal-reproducible-example

**Comment by thecodecafe** [comment]
@periode were you able to find a solution to this problem?

See my definition below.
```go
type Role struct {
	bun.BaseModel `bun:",table:roles"`
	ID            int64         `bun:",pk,autoincrement" bson:"id"`
	Name          string        `bson:"name"`
	DisplayName   string        `bson:"display_name"`
	CreatedAt     time.Time     `bson:"created_at"`
	UpdatedAt     time.Time     `bson:"updated_at"`
	DeletedAt     bun.NullTime  `bun:",nullzero,soft_delete"`
	Users         []User `bun:"m2m:users_roles,join:Role=User"`
}
```
The table `users_roles` exists and I can see it in my db but bun says it doesn't exist, not sure why.

See the error bun prints.
```text
 bun: can't find m2m users_roles table (use db.RegisterModel)
```

I can't seem to figure out what I'm doing wrong, followed the documentation. I believe the value passed to m2m in the relationship definition should be the name of the relationship table, this table exists but bun can't seem to find it, removing it makes my queries run without errors.

**Comment by periode** [comment]
@thecodecafe I'm still quite new to Postgres and DB admin in general, so I ended up switching frameworks and going with GORM.

**Comment by thecodecafe** [comment]
Got it @periode, I may take a look myself for some unknown reason updates don't work either for me.

**Comment by codeliger** [comment]
> Got it @periode, I may take a look myself for some unknown reason updates don't work either for me.

You need to register the M2M model before registering the others. That fixed by bug.
