### ISSUE TITLE
Issue: Panic on Bulk Upsert with Pointer Fields in Slice of Interfaces

### ISSUE THREAD

**Issue by Twsouza** [uptrace/bun#994]
I encountered a panic when attempting to perform a bulk upsert using the bun package with models that have some attributes marked as pointers. These models are stored in a slice of interfaces, and the panic occurs during the upsert operation. The operation works fine if inserting one model at a time but panics when attempting a bulk insert with the same interface.

Here is the model definition that triggers the issue:

```
type Model struct {
	bun.BaseModel `bun:"table:model"`

	Id           int64   `json:"id" bun:"id,pk"`
	Type         string  `json:"type" bun:"type"`
	ParentStatus *string `json:"parent_status" bun:"parent_status"`
}
```

The following code snippet reproduces the panic:

```
package main

import (
	"context"
	"github.com/uptrace/bun"
	"github.com/sirupsen/logrus"
)

type CacheType interface{}

type Model struct {
	bun.BaseModel `bun:"table:model"`

	Id           int64   `json:"id" bun:"id,pk"`
	Type         string  `json:"type" bun:"type"`
	ParentStatus *string `json:"parent_status" bun:"parent_status"`
}

func main() {
	ctx := context.Background()
	db := bun.NewDB(/* database connection setup */)

	caches := []CacheType{}
	model := &Model{
		Id:   1,
		Type: "type",
	}
	caches = append(caches, model)

	_, err := db.NewInsert().Model(&caches).On("CONFLICT (?) DO UPDATE", bun.Ident("id")).Exec(ctx)
	if err != nil {
		logrus.Fatalf("failed to insert caches: %v", err)
	}
}
```

The following panic is observed:

```
panic: reflect: call of reflect.Value.Field on ptr Value

goroutine 1 [running]:
reflect.Value.Field({0x1583d40, 0xc000722c08, 0x16}, 0x21)
	/usr/local/go/src/reflect/value.go:1284 +0x25d
github.com/uptrace/bun/schema.fieldByIndex({0x1583d40, 0xc000722c08, 0x16}, {0xc0006be220, 0x1, 0x1})
	/home/twsouza/go/pkg/mod/github.com/uptrace/bun@v1.2.1/schema/reflect.go:33 +0xb5
github.com/uptrace/bun/schema.(*Field).ScanValue(0xc0006c09a0, {0x1583d40, 0xc000722c08, 0x16}, {0x0, 0x0})
	/home/twsouza/go/pkg/mod/github.com/uptrace/bun@v1.2.1/schema/field.go:117 +0x17a
github.com/uptrace/bun.(*structTableModel).scanColumn(0xc000a40000, {0xc000670000, 0x18}, {0x0, 0x0})
	/home/twsouza/go/pkg/mod/github.com/uptrace/bun@v1.2.1/model_table_struct.go:314 +0x185
github.com/uptrace/bun.(*structTableModel).ScanColumn(0xc000a40000, {0xc000670000, 0x18}, {0x0, 0x0})
	/home/twsouza/go/pkg/mod/github.com/uptrace/bun@v1.2.1/model_table_struct.go:294 +0x7b
github.com/uptrace/bun.(*structTableModel).Scan(0xc000a40000, {0x0, 0x0})
	/home/twsouza/go/pkg/mod/github.com/uptrace/bun@v1.2.1/model_table_struct.go:290 +0xd8
database/sql.convertAssignRows({0x169a900, 0xc000a40000}, {0x0, 0x0}, 0xc000332000)
	/usr/local/go/src/database/sql/convert.go:385 +0x1ef6
database/sql.(*Rows).Scan(0xc000332000, {0xc00086a000, 0x1, 0x1})
	/usr/local/go/src/database/sql/sql.go:3354 +0x4df
github.com/uptrace/bun.(*structTableModel).scanRow(0xc000a40000, {0x17daa00, 0xc000916660}, 0xc000332000, {0xc00086a000, 0x1, 0x1})
	/home/twsouza/go/pkg/mod/github.com/uptrace/bun@v1.2.1/model_table_struct.go:275 +0xbd
github.com/uptrace/bun.(*sliceTableModel).ScanRows(0xc000a40000, {0x17daa00, 0xc000916660}, 0xc000332000)
	/home/twsouza/go/pkg/mod/github.com/uptrace/bun@v1.2.1/model_table_slice.go:76 +0x4f5
github.com/uptrace/bun.(*baseQuery).scan(0xc0006b2680, {0x17daa00, 0xc000916660}, {0x17dafa0, 0xc0006b2680}, {0xc000301000, 0x8c9}, {0x17d5d08, 0xc000a40000}, 0x0)
	/home/twsouza/go/pkg/mod/github.com/uptrace/bun@v1.2.1/query_base.go:569 +0x3d6
github.com/uptrace/bun.(*InsertQuery).scanOrExec(0xc0006b2680, {0x17daae0, 0x1f89600}, {0x0, 0x0, 0x0}, 0x0)
	/home/twsouza/go/pkg/mod/github.com/uptrace/bun@v1.2.1/query_insert.go:598 +0x5c5
github.com/uptrace/bun.(*InsertQuery).Exec(0xc0006b2680, {0x17daae0, 0x1f89600}, {0x0, 0x0, 0x0})
	/home/twsouza/go/pkg/mod/github.com/uptrace/bun@v1.2.1/query_insert.go:556 +0xae
main.main()
	/home/twsouza/src/org/repo/main.go:211 +0x2b6a
```

## Steps to Reproduce
- Define the Model struct with a pointer field.
- Create a slice of interfaces and add an instance of the Model struct to it.
- Attempt to perform a bulk upsert on the slice using bun.NewInsert().Model(&caches).On("CONFLICT (?) DO UPDATE", bun.Ident("id")).Exec(ctx).

## Expected Behavior
The upsert operation should complete without panicking, correctly handling models with pointer fields within a slice of interfaces.

## Actual Behavior
The upsert operation panics with a reflect error when trying to access a field on a pointer value.

Additional Information
Bun version: v1.2.1
Go version: go1.22.1
Database: PostgreSQL

Is there a recommended workaround for this issue? Any guidance or updates on how to resolve this would be greatly appreciated. Thank you!

**Comment by Twsouza** [comment]
Notably, removing the `On("CONFLICT (?) DO UPDATE", bun.Ident("id"))` part makes the code work without panicking but loses the upsert capabilities, meaning it doesn't update on conflicts.
